server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://<mysql-host>:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: <mysql-username>
    password: <mysql-password>
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

minio:
  endpoint: http://<minio-host>:9000
  accessKey: <minio-access-key>
  secretKey: <minio-secret-key>
  bucketName: weblog

jwt:
  issuer: <jwt-issuer>
  secret: <base64-jwt-secret>
  tokenExpireTime: 1440
  tokenHeaderKey: Authorization
  tokenPrefix: Bearer

logging:
  config: classpath:logback-weblog.xml
